version: "3.8"
services:
  postgres-composes:
    container_name: postgres-composes-container
    network_mode: "host"
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_composes_container:/var/lib/postgres

volumes:
  postgres_composes_container:
